// circom_export.go — Generates production Circom circuits with real ci-derived constants
//
// Usage:
//   go run circom_export.go
//
// Outputs:
//   circuits/ci_poseidon_t3_bn254.circom  — t=3, BN254 field, full constants injected
//   circuits/ci_poseidon_t2_bn254.circom  — t=2, BN254 field
//   circuits/ci_poseidon_t4_bn254.circom  — t=4, BN254 field
//   circuits/ci_poseidon_t6_bn254.circom  — t=6, BN254 field
//
// Each generated circuit is fully self-contained — all round constants are
// hardcoded as field literals derived from Ci = 85/27 mod p. No external
// constant files, no runtime computation, no trust required.
//
// To verify any constant independently:
//   K[i] = (85 × prime[i] × 2^64) × inv(27 × (prime[i]+1))  mod p
//
// Author:  Christopher Seekins — Harmony Worldwide / HealChain
// Package: github.com/karmaxul/ci-poseidon
// Date:    June 2026

//go:build ignore

package main

import (
	"fmt"
	"math/big"
	"os"
	"strings"

	ciposeidon "github.com/karmaxul/ci-poseidon"
)

func main() {
	p := ciposeidon.BN254ScalarField

	configs := []struct {
		width  int
		mode   string
		field  string
		prime  *big.Int
		outfile string
	}{
		{2, "circulant", "bn254", p, "circuits/ci_poseidon_t2_bn254.circom"},
		{3, "circulant", "bn254", p, "circuits/ci_poseidon_t3_bn254.circom"},
		{4, "circulant", "bn254", p, "circuits/ci_poseidon_t4_bn254.circom"},
		{6, "circulant", "bn254", p, "circuits/ci_poseidon_t6_bn254.circom"},
	}

	for _, cfg := range configs {
		src := generateCircom(cfg.width, cfg.mode, cfg.field, cfg.prime)
		if err := os.WriteFile(cfg.outfile, []byte(src), 0644); err != nil {
			fmt.Fprintf(os.Stderr, "error writing %s: %v\n", cfg.outfile, err)
			os.Exit(1)
		}
		fmt.Printf("✓ Generated %s (%d constants)\n", cfg.outfile,
			ciposeidon.GetPermutationParams(cfg.width).ConstantsNeeded())
	}
	fmt.Println("\nAll circuits generated. Verify any constant with:")
	fmt.Println("  K[i] = (85 * prime[i] * 2^64) * inv(27 * (prime[i]+1)) mod p")
}

// generateCircom produces a fully self-contained Circom circuit for the
// given width and field, with all round constants hardcoded as field literals.
func generateCircom(width int, mode, fieldLabel string, prime *big.Int) string {
	pp := ciposeidon.GetPermutationParams(width)
	rc := ciposeidon.NewRoundConstants(width, prime)
	mdsSeeds := mdsCirculantSeeds(width)

	var b strings.Builder

	// Header
	b.WriteString("pragma circom 2.1.0;\n\n")
	b.WriteString(fmt.Sprintf("/*\n"))
	b.WriteString(fmt.Sprintf(" * ci_poseidon_t%d_%s.circom\n", width, fieldLabel))
	b.WriteString(fmt.Sprintf(" * AUTO-GENERATED by circom_export.go — DO NOT EDIT MANUALLY\n"))
	b.WriteString(fmt.Sprintf(" *\n"))
	b.WriteString(fmt.Sprintf(" * Width:          t=%d\n", width))
	b.WriteString(fmt.Sprintf(" * Field:          %s scalar field\n", strings.ToUpper(fieldLabel)))
	b.WriteString(fmt.Sprintf(" * Full rounds:    rf=%d\n", pp.FullRounds))
	b.WriteString(fmt.Sprintf(" * Partial rounds: rp=%d\n", pp.PartialRounds))
	b.WriteString(fmt.Sprintf(" * Total rounds:   %d\n", pp.TotalRounds()))
	b.WriteString(fmt.Sprintf(" * Constants:      %d (derived from Ci=85/27)\n", pp.ConstantsNeeded()))
	b.WriteString(fmt.Sprintf(" * MDS:            circulant baseline seeds %v\n", mdsSeeds))
	b.WriteString(fmt.Sprintf(" *\n"))
	b.WriteString(fmt.Sprintf(" * Constraint estimate:\n"))
	b.WriteString(fmt.Sprintf(" *   Full rounds:    %d × %d × 3 = %d\n",
		pp.FullRounds, width, pp.FullRounds*width*3))
	b.WriteString(fmt.Sprintf(" *   Partial rounds: %d × 1 × 3 = %d\n",
		pp.PartialRounds, pp.PartialRounds*3))
	b.WriteString(fmt.Sprintf(" *   Total constraints: ~%d\n",
		pp.FullRounds*width*3+pp.PartialRounds*3))
	b.WriteString(fmt.Sprintf(" *\n"))
	b.WriteString(fmt.Sprintf(" * Verify constant K[i]: (85*prime[i]*2^64)*inv(27*(prime[i]+1)) mod p\n"))
	b.WriteString(fmt.Sprintf(" */\n\n"))

	// Pow5 template
	b.WriteString("// x^5 S-box (3 multiplication constraints)\n")
	b.WriteString("template Pow5() {\n")
	b.WriteString("    signal input  in;\n")
	b.WriteString("    signal output out;\n")
	b.WriteString("    signal x2;\n")
	b.WriteString("    signal x4;\n")
	b.WriteString("    x2  <== in * in;\n")
	b.WriteString("    x4  <== x2 * x2;\n")
	b.WriteString("    out <== x4 * in;\n")
	b.WriteString("}\n\n")

	// MDS template
	b.WriteString(fmt.Sprintf("// Circulant MDS matrix t=%d (linear — zero multiplication constraints)\n", width))
	b.WriteString(fmt.Sprintf("template MDSMul_t%d() {\n", width))
	b.WriteString(fmt.Sprintf("    signal input  in[%d];\n", width))
	b.WriteString(fmt.Sprintf("    signal output out[%d];\n", width))
	for i := 0; i < width; i++ {
		terms := make([]string, width)
		for j := 0; j < width; j++ {
			seed := mdsSeeds[((j-i)+width)%width]
			terms[j] = fmt.Sprintf("%d*in[%d]", seed, j)
		}
		b.WriteString(fmt.Sprintf("    out[%d] <== %s;\n", i, strings.Join(terms, " + ")))
	}
	b.WriteString("}\n\n")

	// Full round template
	b.WriteString(fmt.Sprintf("// Full round: S-box ALL elements + MDS\n"))
	b.WriteString(fmt.Sprintf("// %d multiplication constraints per full round\n", width*3))
	b.WriteString(fmt.Sprintf("template FullRound_t%d(", width))
	rcParams := make([]string, width)
	for e := 0; e < width; e++ {
		rcParams[e] = fmt.Sprintf("rc%d", e)
	}
	b.WriteString(strings.Join(rcParams, ", "))
	b.WriteString(") {\n")
	b.WriteString(fmt.Sprintf("    signal input  in[%d];\n", width))
	b.WriteString(fmt.Sprintf("    signal output out[%d];\n", width))
	b.WriteString(fmt.Sprintf("    component sb[%d];\n", width))
	b.WriteString(fmt.Sprintf("    for (var i = 0; i < %d; i++) { sb[i] = Pow5(); }\n", width))
	for e := 0; e < width; e++ {
		b.WriteString(fmt.Sprintf("    sb[%d].in <== in[%d] + rc%d;\n", e, e, e))
	}
	b.WriteString(fmt.Sprintf("    component mds = MDSMul_t%d();\n", width))
	for e := 0; e < width; e++ {
		b.WriteString(fmt.Sprintf("    mds.in[%d] <== sb[%d].out;\n", e, e))
	}
	for e := 0; e < width; e++ {
		b.WriteString(fmt.Sprintf("    out[%d] <== mds.out[%d];\n", e, e))
	}
	b.WriteString("}\n\n")

	// Partial round template
	b.WriteString("// Partial round: S-box FIRST element only + MDS\n")
	b.WriteString("// 3 multiplication constraints per partial round\n")
	b.WriteString(fmt.Sprintf("template PartialRound_t%d(", width))
	b.WriteString(strings.Join(rcParams, ", "))
	b.WriteString(") {\n")
	b.WriteString(fmt.Sprintf("    signal input  in[%d];\n", width))
	b.WriteString(fmt.Sprintf("    signal output out[%d];\n", width))
	b.WriteString("    component sb = Pow5();\n")
	b.WriteString("    sb.in <== in[0] + rc0;\n")
	b.WriteString(fmt.Sprintf("    component mds = MDSMul_t%d();\n", width))
	b.WriteString("    mds.in[0] <== sb.out;\n")
	for e := 1; e < width; e++ {
		b.WriteString(fmt.Sprintf("    mds.in[%d] <== in[%d] + rc%d;\n", e, e, e))
	}
	for e := 0; e < width; e++ {
		b.WriteString(fmt.Sprintf("    out[%d] <== mds.out[%d];\n", e, e))
	}
	b.WriteString("}\n\n")

	// Main permutation template with hardcoded constants
	b.WriteString(fmt.Sprintf("// CiPoseidon_t%d — full permutation with ci-derived constants\n", width))
	b.WriteString(fmt.Sprintf("template CiPoseidon_t%d() {\n", width))
	b.WriteString(fmt.Sprintf("    signal input  in[%d];\n", width))
	b.WriteString(fmt.Sprintf("    signal output out[%d];\n\n", width))

	// Track signal names through rounds
	prevSignals := make([]string, width)
	for e := 0; e < width; e++ {
		prevSignals[e] = fmt.Sprintf("in[%d]", e)
	}

	roundIdx := 0

	// Initial AddRoundConstants
	b.WriteString("    // Round 0: initial AddRoundConstants\n")
	arcSignals := make([]string, width)
	for e := 0; e < width; e++ {
		sigName := fmt.Sprintf("arc_%d_%d", roundIdx, e)
		arcSignals[e] = sigName
		rc0 := rc.Constants[roundIdx][e]
		b.WriteString(fmt.Sprintf("    signal %s;\n", sigName))
		b.WriteString(fmt.Sprintf("    %s <== %s + %s;\n", sigName, prevSignals[e], rc0.String()))
	}
	prevSignals = arcSignals
	roundIdx++

	// First half full rounds
	b.WriteString(fmt.Sprintf("\n    // Full rounds 1..%d\n", pp.FullRounds/2))
	for i := 0; i < pp.FullRounds/2; i++ {
		sigBase := fmt.Sprintf("fr1_%d", i)
		b.WriteString(fmt.Sprintf("    component %s = FullRound_t%d(", sigBase, width))
		rcArgs := make([]string, width)
		for e := 0; e < width; e++ {
			rcArgs[e] = rc.Constants[roundIdx][e].String()
		}
		b.WriteString(strings.Join(rcArgs, ", "))
		b.WriteString(");\n")
		for e := 0; e < width; e++ {
			b.WriteString(fmt.Sprintf("    %s.in[%d] <== %s;\n", sigBase, e, prevSignals[e]))
		}
		nextSignals := make([]string, width)
		for e := 0; e < width; e++ {
			nextSignals[e] = fmt.Sprintf("%s.out[%d]", sigBase, e)
		}
		prevSignals = nextSignals
		roundIdx++
	}

	// Partial rounds
	b.WriteString(fmt.Sprintf("\n    // Partial rounds 1..%d\n", pp.PartialRounds))
	for i := 0; i < pp.PartialRounds; i++ {
		sigBase := fmt.Sprintf("pr_%d", i)
		b.WriteString(fmt.Sprintf("    component %s = PartialRound_t%d(", sigBase, width))
		rcArgs := make([]string, width)
		for e := 0; e < width; e++ {
			rcArgs[e] = rc.Constants[roundIdx][e].String()
		}
		b.WriteString(strings.Join(rcArgs, ", "))
		b.WriteString(");\n")
		for e := 0; e < width; e++ {
			b.WriteString(fmt.Sprintf("    %s.in[%d] <== %s;\n", sigBase, e, prevSignals[e]))
		}
		nextSignals := make([]string, width)
		for e := 0; e < width; e++ {
			nextSignals[e] = fmt.Sprintf("%s.out[%d]", sigBase, e)
		}
		prevSignals = nextSignals
		roundIdx++
	}

	// Second half full rounds
	b.WriteString(fmt.Sprintf("\n    // Full rounds %d..%d\n", pp.FullRounds/2+1, pp.FullRounds))
	for i := 0; i < pp.FullRounds/2; i++ {
		sigBase := fmt.Sprintf("fr2_%d", i)
		b.WriteString(fmt.Sprintf("    component %s = FullRound_t%d(", sigBase, width))
		rcArgs := make([]string, width)
		for e := 0; e < width; e++ {
			rcArgs[e] = rc.Constants[roundIdx][e].String()
		}
		b.WriteString(strings.Join(rcArgs, ", "))
		b.WriteString(");\n")
		for e := 0; e < width; e++ {
			b.WriteString(fmt.Sprintf("    %s.in[%d] <== %s;\n", sigBase, e, prevSignals[e]))
		}
		nextSignals := make([]string, width)
		for e := 0; e < width; e++ {
			nextSignals[e] = fmt.Sprintf("%s.out[%d]", sigBase, e)
		}
		prevSignals = nextSignals
		roundIdx++
	}

	// Output
	b.WriteString("\n    // Output\n")
	for e := 0; e < width; e++ {
		b.WriteString(fmt.Sprintf("    out[%d] <== %s;\n", e, prevSignals[e]))
	}
	b.WriteString("}\n\n")

	// Main component for t=3 (most common use case)
	if width == 3 {
		b.WriteString("// Convenience: single-output hash for 2 inputs\n")
		b.WriteString("template CiPoseidonHash2() {\n")
		b.WriteString("    signal input  in[2];\n")
		b.WriteString("    signal output out;\n")
		b.WriteString("    component h = CiPoseidon_t3();\n")
		b.WriteString("    h.in[0] <== in[0];\n")
		b.WriteString("    h.in[1] <== in[1];\n")
		b.WriteString("    h.in[2] <== 2; // domain separation tag\n")
		b.WriteString("    out <== h.out[0];\n")
		b.WriteString("}\n\n")
		b.WriteString("component main = CiPoseidonHash2();\n")
	}

	return b.String()
}

// mdsCirculantSeeds returns the circulant seed values for each width.
func mdsCirculantSeeds(width int) []int64 {
	switch width {
	case 2:
		return []int64{2, 1}
	case 3:
		return []int64{2, 1, 1}
	case 4:
		return []int64{5, 7, 1, 3}
	case 6:
		return []int64{10, 11, 13, 5, 2, 1}
	default:
		return []int64{1}
	}
}
